### ISSUE TITLE
Interlock only detecting events on UCP node + nginx not getting updated

### ISSUE THREAD

**Issue by bosiwow** [ehazlett/interlock#127] opened 2016-04-26 09:08 UTC
Hello,

first of all, great project you're developing. 
I have some trouble setting up interlock. i.e. interlock only detects events from the UCP controller and not on the other nodes, while docker-events detects them all.

Also, for some reason the nginx loadbalancer I'm using is not getting updated by interlock. Can somebody please take a look?
The entire explanation+logs of the problem can be found on the docker forum:
https://forums.docker.com/t/docker-interlock-not-detecting-events-apart-from-controller-node/9847

**Comment by ehazlett** [comment] 2016-04-26 15:48
Hello!  Can you try to connect it to the Swarm event stream to see if you are getting the events outside of UCP?  That way we can isolate the issue (default port for Swarm with UCP is 2376).

Also, how are you launching containers?  What labels are you specifying?

**Comment by bosiwow** [comment] 2016-04-26 17:16
Hi, thank you for your reply.
What do you mean with trying to connect it to the swarm event stream?
Right now my config.toml looks like this (192.168.123.14 is the UCP controller node)

`ListenAddr = ":8080"
DockerURL = "tcp://192.168.123.14:2376"
TLSCACert = "/certs/ca.pem"
TLSCert = "/certs/server.pem" 
TLSKey = "/certs/server-key.pem" 

[[Extensions]]
Name = "nginx"
ConfigPath = "/etc/nginx/nginx.conf"
PidPath = "/etc/nginx/nginx.pid"
MaxConn = 1024
Port = 80`

The docker-compose-v1.1.yml looks like this:
```
version : "2"

services:
interlock:
    image: ehazlett/interlock:1.1.0
    command: -D run -c /bin/config.toml
    ports:
        - 8080
    volumes:
        - ./config.toml:/bin/config.toml
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/boot2docker:/certs       <----------------------- changed
    restart: always
    network_mode: "bridge"
nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - 80:80
    labels:
      - "interlock.ext.name=nginx"
    depends_on:
      - interlock
    network_mode: "bridge"
    restart: always
```

I'm launching the containers with docker-compose on a cli that has the client bundle for ucp. The labels I specified are: 
interlock.hostname=results 
interlock.domain=myenterprise.com
I followed the guide on docker to setup interlock and nginx.

**Comment by ehazlett** [comment] 2016-04-26 17:28
I believe the cert path should be `/var/lib/boot2docker/tls`.  Can you report the logs from Interlock here?  Thanks.

**Comment by bosiwow** [comment] 2016-04-27 07:30
Hello,
thank you for the reply.
So here is the output of docker-machine ls
```

esxdockerengine1   -        vmwarevsphere   Running   tcp://192.168.123.14:2376           v1.10.3 (this node runs my controllers)
esxdockerengine2   -        vmwarevsphere   Running   tcp://192.168.123.15:2376           v1.10.3 (this node will run some apps (node1 and node3 will also run some apps))
esxdockerengine3   -        vmwarevsphere   Running   tcp://192.168.123.39:2376           v1.11.0 (this will be my loadbalancing node)
```

So to start I ssh'd into the esxdockerengine3. There I cloned your git repo. I changed the config.toml like in my previous post (but with serverkey.pem instead of server-key.pem) and docker-compose-v1.1.yml also like in my previous post 
(but with /var/lib/boot2docker/tls as cert path).

After that I did  (not sure if I still have to do? but docker-compose logs complains sometimes about it):
`export CONTROLLER_IP=192.168.123.14`

Followed by this command:
`docker-compose -f docker-compose-v1.1.yml up -d`

Then I checked my logs (docker-compose logs) and got the following error:

```

root@esxdockerengine3:/home/docker/interlock-lbs/interlock-nginx# docker-compose logs
Attaching to interlocknginx_nginx_1, interlocknginx_interlock_1
interlock_1  | time="2016-04-27T06:32:31Z" level=info msg="interlock 1.1.0 (8a68c99)"
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="loading config from: /bin/config.toml"
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="using tls for communication with docker"
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="docker client: url=tcp://192.168.123.14:2376"
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="loading extension: name=nginx"
interlock_1  | time="2016-04-27T06:32:31Z" level=info msg="interlock node: id=0f292ba12000cf2e0d56d8e36a1f803bf3f3f7773f27ef3cc1a88ed6492f3e03" ext=lb
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="starting event handling"
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="event received: status=interlock-start id=0 type= action="
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T06:32:31Z" level=debug msg="triggering reload" ext=lb
interlock_1  | time="2016-04-27T06:32:32Z" level=error msg="event stream fail; attempting to reconnect"
interlock_1  | time="2016-04-27T06:32:32Z" level=info msg="waiting for event stream to become ready"
interlock_1  | time="2016-04-27T06:32:32Z" level=debug msg="event stream not yet ready; retrying"
interlock_1  | time="2016-04-27T06:32:32Z" level=debug msg="reaping key: reload"
interlock_1  | time="2016-04-27T06:32:32Z" level=debug msg="triggering reload from cache" ext=lb
interlock_1  | time="2016-04-27T06:32:32Z" level=debug msg="checking to reload" ext=lb
interlock_1  | time="2016-04-27T06:32:32Z" level=debug msg="updating load balancers" ext=lb
interlock_1  | time="2016-04-27T06:32:32Z" level=error msg="Get https://192.168.123.14:2376/v1.15/containers/json?all=0&size=0: remote error: bad certificate" ext=lb
interlock_1  | time="2016-04-27T06:32:33Z" level=debug msg="event stream not yet ready; retrying"
interlock_1  | time="2016-04-27T06:32:34Z" level=debug msg="event stream not yet ready; retrying"
interlock_1  | time="2016-04-27T06:32:35Z" level=debug msg="event stream not yet ready; retrying"
interlock_1  | time="2016-04-27T06:32:36Z" level=debug msg="event stream not yet ready; retrying"
interlock_1  | time="2016-04-27T06:32:37Z" level=debug msg="event stream not yet ready; retrying"

```

So I decided to try again with server-key.pem in the config.toml and /var/lib/boot2docker/ for the cert path.
I deleted the previous 2 containers from within the UCP UI and relaunched the containers (docker-compose -f docker-compose-v1.1.yml up -d). Now the logs look like this (I think it looks better, but I'm not an expert ofc)

```
root@esxdockerengine3:/home/docker/interlock-lbs/interlock-nginx# docker-compose logs
Attaching to interlocknginx_nginx_1, interlocknginx_interlock_1
interlock_1  | time="2016-04-27T06:34:55Z" level=info msg="interlock 1.1.0 (8a68c99)"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="loading config from: /bin/config.toml"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="using tls for communication with docker"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="docker client: url=tcp://192.168.123.14:2376"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="loading extension: name=nginx"
interlock_1  | time="2016-04-27T06:34:55Z" level=info msg="interlock node: id=3f694e331f2de13fd06ebcdaad003e0dbc1dc7b953c36f21d74beab96679b16c" ext=lb
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="starting event handling"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="event received: status=interlock-start id=0 type= action="
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="triggering reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="reaping key: reload"
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="triggering reload from cache" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="checking to reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="updating load balancers" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="generating proxy config" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="proxy config path: /etc/nginx/nginx.conf" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="saving proxy config" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="signaling reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="triggering proxy network cleanup" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=info msg="reload duration: 53.76ms" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="checking to remove proxy containers from networks" ext=lb
```


So now I opened a cli, where I got the cli docker client bundle configured and ran a docker info to make sure I was connected to the swarm.
The docker info came back positive, so I was connected to the swarm. Then I ran the following docker compose file using the command (docker-compose up -d)

```
version: "2"

services:
  voting-app:
    image: dtr.local/offsite/mycompanyoffsitevoter
    restart: always
	environment:
      - "constraint:type==secondary"                        <----------------This is the second node
    ports:
      - "80"
    networks:
      - voteapp
    labels:
      interlock.hostname: "vote"
      interlock.domain: "mycompany.local"
  result-app:
    image: dtr.local/offsite/mycompanyoffsiteresult
    restart: always
    environment: 
      - "constraint:type==loadbalancing"                   <------------------ This is the third node
    ports:
      - "80"
    networks:
      - voteapp
    labels:
      interlock.hostname: "results"
      interlock.domain: "mycompany.local"
  worker:
    image: docker/example-voting-app-worker
    restart: always
    networks:
      voteapp:
        aliases:
          - workers
  redis:
    image: redis
    restart: always
    ports:
      - "6379"
    networks:
      - voteapp
    container_name: redisdocker 

  db:
    image: postgres:9.4
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - voteapp
    container_name: db
volumes:
  db-data:

networks:
  voteapp:
```

  
Once all the containers started (verified in UCP apps UI) I went back to node3 and ran the docker-compose logs command.

```
root@esxdockerengine3:/home/docker/interlock-lbs/interlock-nginx# docker-compose logs
Attaching to interlocknginx_nginx_1, interlocknginx_interlock_1
interlock_1  | time="2016-04-27T06:34:55Z" level=info msg="interlock 1.1.0 (8a68c99)"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="loading config from: /bin/config.toml"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="using tls for communication with docker"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="docker client: url=tcp://192.168.123.14:2376"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="loading extension: name=nginx"
interlock_1  | time="2016-04-27T06:34:55Z" level=info msg="interlock node: id=3f694e331f2de13fd06ebcdaad003e0dbc1dc7b953c36f21d74beab96679b16c" ext=lb
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="starting event handling"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="event received: status=interlock-start id=0 type= action="
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="triggering reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="reaping key: reload"
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="triggering reload from cache" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="checking to reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="updating load balancers" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="generating proxy config" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="proxy config path: /etc/nginx/nginx.conf" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="saving proxy config" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="signaling reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="triggering proxy network cleanup" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=info msg="reload duration: 53.76ms" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="checking to remove proxy containers from networks" ext=lb
interlock_1  | time="2016-04-27T07:04:25Z" level=debug msg="event received: status= id= type=volume action=create"      <--------- new line 
interlock_1  | time="2016-04-27T07:04:25Z" level=debug msg="notifying extension: lb"	 								<--------- new line
interlock_1  | time="2016-04-27T07:13:34Z" level=debug msg="event received: status= id= type=volume action=create"		<--------- new line
interlock_1  | time="2016-04-27T07:13:34Z" level=debug msg="notifying extension: lb"	   <--------- new line	
```							

As you can see, no notification about new containers (because all the containers were launched on node2 and node3, not on the controller node)

So what I did next is: I ssh'd into the esxdockerengine1 (the ucp controller node) and launched 2 containers (using the docker run command on node1) (one died because of a misconfiguration, but the point is, they were detected).
On the docker-compose logs command on node3 I saw them:

```
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="starting event handling"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="event received: status=interlock-start id=0 type= action="
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T06:34:55Z" level=debug msg="triggering reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="reaping key: reload"
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="triggering reload from cache" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="checking to reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="updating load balancers" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="generating proxy config" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="proxy config path: /etc/nginx/nginx.conf" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="saving proxy config" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="signaling reload" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="triggering proxy network cleanup" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=info msg="reload duration: 53.76ms" ext=lb
interlock_1  | time="2016-04-27T06:34:56Z" level=debug msg="checking to remove proxy containers from networks" ext=lb
interlock_1  | time="2016-04-27T07:04:25Z" level=debug msg="event received: status= id= type=volume action=create"
interlock_1  | time="2016-04-27T07:04:25Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:13:34Z" level=debug msg="event received: status= id= type=volume action=create"
interlock_1  | time="2016-04-27T07:13:34Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:20:19Z" level=debug msg="event received: status=create id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248 type=container action=create"
interlock_1  | time="2016-04-27T07:20:19Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:20:19Z" level=debug msg="event received: status=attach id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248 type=container action=attach"
interlock_1  | time="2016-04-27T07:20:19Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="event received: status= id= type=network action=connect"
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="inspecting container: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="checking container labels: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="checking container ports: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="no ports exposed; ignoring: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="event received: status=start id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248 type=container action=start"
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="inspecting container: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="checking container labels: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="checking container ports: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:20Z" level=debug msg="no ports exposed; ignoring: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:21Z" level=debug msg="event received: status=die id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248 type=container action=die"
interlock_1  | time="2016-04-27T07:20:21Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:20:22Z" level=debug msg="event received: status= id= type=network action=disconnect"
interlock_1  | time="2016-04-27T07:20:22Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:20:22Z" level=debug msg="inspecting container: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:22Z" level=debug msg="checking container labels: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:22Z" level=debug msg="checking container ports: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:20:22Z" level=debug msg="no ports exposed; ignoring: id=ca5178c64ff0720a1c98b605c791a1484a92fa368a7e85025af0f5b04061f248" ext=lb
interlock_1  | time="2016-04-27T07:21:11Z" level=debug msg="event received: status=create id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e type=container action=create"
interlock_1  | time="2016-04-27T07:21:11Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:21:11Z" level=debug msg="event received: status=attach id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e type=container action=attach"
interlock_1  | time="2016-04-27T07:21:11Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:21:12Z" level=debug msg="event received: status= id= type=network action=connect"
interlock_1  | time="2016-04-27T07:21:12Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:21:12Z" level=debug msg="inspecting container: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="checking container labels: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="checking container ports: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="no ports exposed; ignoring: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="event received: status=start id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e type=container action=start"
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="notifying extension: lb"
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="inspecting container: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="checking container labels: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="checking container ports: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="no ports exposed; ignoring: id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e" ext=lb
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="event received: status=resize id=e202ec8db72f016d1115122e38e9125c6b49249defa0ac6fd3fc79730fa4236e type=container action=resize"
interlock_1  | time="2016-04-27T07:21:13Z" level=debug msg="notifying extension: lb"
```



Now I'm not sure if I'm attached to the swarm event stream like you asked me to do in your first reply. How do I do that?

**Comment by bosiwow** [comment] 2016-04-28 08:21
Here are my "ucp containers", maybe I'm just listening at the wrong port?
```
a3be99741d5e        docker/ucp-swarm:1.0.4                  "/swarm join --discov"   6 days ago          Up 19 hours                 2375/tcp
50c7a5ac72cf        docker/ucp-proxy:1.0.4                  "/bin/run"               6 days ago          Up 19 hours                 192.168.123.39:12376->2376/tcp
138bc70eab41        dtr.local/user/ubuntucustom             "/bin/bash"              13 days ago         Exited (0) 11 minutes ago
0fd64bb0eaa2        dtr.local/user/ubuntucustom             "/bin/bash"              13 days ago         Exited (0) 5 days ago
402b56931221        dtr.local/user/ubuntucustom             "/bin/bash"              13 days ago         Exited (0) 2 days ago
3be7068afd6d        docker/ucp-swarm:1.0.3                  "/swarm join --discov"   2 weeks ago         Up 19 hours                 2375/tcp
9470a7478f12        docker/ucp-proxy:1.0.3                  "/bin/run"               2 weeks ago         Up 19 hours                 192.168.123.15:12376->2376/tcp
bed0b9743a80        docker/ucp-controller:1.0.3             "/bin/controller serv"   2 weeks ago         Up 19 hours                 192.168.123.14:443->8080/tcp
893842f7f9ad        docker/ucp-cfssl:1.0.3                  "/bin/cfssl serve -ad"   2 weeks ago         Up 19 hours                 8888/tcp, 192.168.123.14:12381->12381/tcp
09df9214f863        docker/ucp-cfssl:1.0.3                  "/bin/cfssl serve -ad"   2 weeks ago         Up 19 hours                 8888/tcp, 192.168.123.14:12382->12382/tcp
556e4962e34d        docker/ucp-swarm:1.0.3                  "/swarm manage --tlsv"   2 weeks ago         Up 19 hours                 192.168.123.14:3376->2375/tcp
fed10a85336c        docker/ucp-swarm:1.0.3                  "/swarm join --discov"   2 weeks ago         Up 19 hours                 2375/tcp
d7a98d4b8b27        docker/ucp-proxy:1.0.3                  "/bin/run"               2 weeks ago         Up 19 hours                 192.168.123.14:12376->2376/tcp
940d4a291af9        docker/ucp-etcd:1.0.3                   "/bin/etcd --data-dir"   2 weeks ago         Up 19 hours                 2380/tcp, 4001/tcp, 7001/tcp, 192.168.123.14:12380->12380/tcp, 192.168.123
```

**Comment by ehazlett** [comment] 2016-04-28 13:46
Yes sorry I didn't realize you were using boot2docker or docker machine.  Since Docker Machine uses 2376 for the local Engine ports you must use the Swarm port for interlock (in your case 3376).

As for the container ports not showing up, are you sure you used this version of the compose file?  The variable makes it sound like it's including another file and possibly overwriting some service or something.

You also need to make sure you either have a local host entry (i.e. /etc/hosts) or the name is resolvable by DNS as nginx cannot route the traffic to the proper backend without the host header.

**Comment by bosiwow** [comment] 2016-04-29 06:27
Thank you for the reply, yes I have set up /etc/hosts (otherwise i wouldn't get a 503 I guess).
What do you mean with

> As for the container ports not showing up, are you sure you used this version of the compose file? The variable makes it sound like it's including another file and possibly overwriting some service or something.
Which ports aren't showing up?

**Comment by ehazlett** [comment] 2016-04-29 12:13
Actually you will only get 503 when you send a host that haproxy doesn't
know.

There is no variable with that name which says that you either used a
different file or something is being included that would cause that error.

I created an example specifically for UCP. It happens to use Docker Machine
but you can get it to work with non Docker Machine with minimal effort
(change the Swarm host). The example is here
https://github.com/ehazlett/interlock/tree/master/docs/examples/nginx-ucp

**Comment by arhea** [comment] 2016-05-03 14:21
I am experiencing this issue as well with UCP deployed to a cluster of Red Hat Servers.

Steps to Reproduce:
1. Deploy Interlock and Nginx
2. Start other applications. Everything loads through the proxy no issues.
3. Restart the containers through the UCP UI or through docker-compose and I receive a 502 Bad Gateway. Upon investigating the logs I notice that the port number doesn't align to that displayed by UCP.
4. Restart Interlock and Nginx everything works fine again.

**Comment by ehazlett** [comment] 2016-05-04 03:53
@arhea are you getting events from the manager?  I've seen occasional issues where the Swarm event stream stops sending events.  Restarting the Swarm managers and then Interlock (after) usually fixes.

**Comment by ehazlett** [comment] 2016-05-04 07:09
Ok I found a bug in the restart logic for the proxies.  I've fixed and updated `ehazlett/interlock:master`.  Can you try that and see if it solves the issue?  Sorry and thanks for your patience :)

**Comment by arhea** [comment] 2016-05-04 16:24
@ehazlett I haven't look into it that deep. My current inspection just shows that after restart of a container and the port number changes that new port isn't reflected in the nginx configuration. I have switched our development environment over to the master image and I will monitor the logs next time (if it pops up) and pass those along.

**Comment by ehazlett** [comment] 2016-05-04 18:02
@arhea awesome thank you for the update!

**Comment by deuch** [comment] 2016-05-18 15:28
Hi guy, doesn't seem to work in my setup (3 UCP Controllers and 5 UCP Nodes). If i deploy interlock+ nginx on my node, only containers deployed on the UCP Controllers are detected by Interlock ... Every container deployed on the 5 UCP nodes are not detected by Interlock.

I'm using UCP 1.1.0, set my master controller FQDN as UCP_URL for interlock (port 2376). My cluster works fine in UCP, i can deploy containers on the cluster from the GIU or via CLI with bundle.

I've tested the 1.1.0, 1.1.1 and Master version of interlock with no luck. Even with the docker-compose.yml fileuse in the UCP sample. I've tried to set the consiguration in etcd with the same behaviour.

UCP 1.0.4 and Interlock 1.1.0 worked perfectly before the upgrade to 1.1.0.

**Comment by ehazlett** [comment] 2016-05-18 15:39
I've seen this happen when the Swarm event stream stops sending events.
Try restarting your Swarm managers (one at a time for leader election).  It
should come back.

**Comment by arhea** [comment] 2016-05-18 15:40
@ehazlett the latest cut of 1.1.1 seems to be working great. No issues on my end.

**Comment by ehazlett** [comment] 2016-05-27 18:10
@arhea thanks!  i'm going to close this as I cannot duplicate.  please re-open or open a new issue if you experience again.

**Closed by ehazlett** 2016-05-27 18:10 UTC
