### ISSUE TITLE
Validataion for nginx.conf file

### ISSUE THREAD

**Issue by pvnovarese** [ehazlett/interlock#218] opened 2017-06-02 17:43 UTC
One of our end-users (developer) had updated his docker-compose with wrong syntax for interlock.hostname & redeployed the container.  This updated the ngnix.conf  - as a result ngnix became unresponsive.   Is there a way to validate the ngnix.conf file automatically?

**Comment by ehazlett** [comment] 2017-06-02 18:48
duplicate of #217.  closing.

**Closed by ehazlett** 2017-06-02 18:48 UTC
