### ISSUE TITLE
Interlock does not generate/save proxy config files

### ISSUE THREAD

**Issue by inf-rno** [ehazlett/interlock#114] opened 2016-04-06 13:18 UTC
I'm deploying interlock onto a swarm in Azure using the Azure Container Service template. It is basically a swarm with one master and a couple of nodes.

Here is my compose file:

```
version: '2'
volumes:
  haproxy:
services:
  # nginx service to serve static client files
  nginx:
    image: boilerangularloop/boilerangularloop_nginx
    restart: always
    ports:
      - '8080'
    labels:
        - "interlock.hostname=boilagents"
        - "interlock.domain=eastus.cloudapp.azure.com"

  #interlock
  interlock:
    image: ehazlett/interlock:1.1.0
    environment: 
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"

            [[Extensions]]
              Name = "haproxy"
              ConfigPath = "/usr/local/etc/haproxy/haproxy.cfg"
              PidPath = "/run/haproxy.pid"
              MaxConn = 1024
              Port = 80
              AdminUser = "admin"
              AdminPass = "interlock"
    command: -D run
    ports:
        - '8080:8080'
    volumes:
      - haproxy:/usr/local/etc/haproxy

  #loadbalancer
  haproxy:
    image: haproxy:latest
    ports:
        - '80:80'
        - '443:443'
    labels:
        - "interlock.ext.name=haproxy"
    depends_on: 
      - interlock
    volumes:
      - haproxy:/usr/local/etc/haproxy
```

I can see the haproxy volume being created and mounted however interlock doesn't seem to generate the haproxy.cfg file and hence the haproxy service dies. Same happens if I use the nginx extension instead.

Here are the logs:

```
interlock_1 | time="2016-04-06T13:10:35Z" level=info msg="interlock 1.1.0 (8a68c99)"
interlock_1 | time="2016-04-06T13:10:35Z" level=debug msg="loading config from environment"
interlock_1 | time="2016-04-06T13:10:35Z" level=debug msg="docker client: url=tcp://172.16.0.5:2375"
interlock_1 | time="2016-04-06T13:10:35Z" level=debug msg="loading extension: name=haproxy"
interlock_1 | time="2016-04-06T13:10:35Z" level=info msg="interlock node: id=6a62b5554c670e663ae42b1d4f46bd46c4701e049fe252c8d8bfd6853f100f1e" ext=lb
interlock_1 | time="2016-04-06T13:10:35Z" level=debug msg="starting event handling"
interlock_1 | time="2016-04-06T13:10:35Z" level=debug msg="event received: status=interlock-start id=0 type= action="
interlock_1 | time="2016-04-06T13:10:35Z" level=debug msg="notifying extension: lb"
interlock_1 | time="2016-04-06T13:10:35Z" level=debug msg="triggering reload" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="reaping key: reload"
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="triggering reload from cache" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="checking to reload" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="updating load balancers" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="generating proxy config" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=info msg="boilagents.eastus.cloudapp.azure.com: upstream=10.0.0.5:32799 container=vagrant_nginx_1" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="alias domains: []" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="adding host name=boilagents_eastus_cloudapp_azure_com domain=boilagents.eastus.cloudapp.azure.com" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="proxy config path: /usr/local/etc/haproxy/haproxy.cfg" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="saving proxy config" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="calculating restart across interlock nodes: num=1" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="proxy containers to restart: num=0 containers=" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="signaling reload" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="dropping SYN packets to trigger client re-send" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="&{/sbin/iptables [/sbin/iptables -I INPUT -p tcp --dport 80 --syn -j DROP] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=warning msg="error signaling clients to resend; you will notice dropped packets: exit status 3" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="resuming SYN packets" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="&{/sbin/iptables [/sbin/iptables -I INPUT -p tcp --dport 80 --syn -j DROP] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=warning msg="error signaling clients to resume; you will notice dropped packets: exit status 3" ext=haproxy
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="triggering proxy network cleanup" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=info msg="reload duration: 32.68ms" ext=lb
interlock_1 | time="2016-04-06T13:10:36Z" level=debug msg="checking to remove proxy containers from networks" ext=lb
haproxy_1   | <7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds
haproxy_1   | [ALERT] 096/131038 (7) : Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
haproxy_1   | <5>haproxy-systemd-wrapper: exit, haproxy RC=256
vagrant_haproxy_1 exited with code 0
```

As you see, it logs both generating and saving proxy config. But if I exec into the interlock container and look at the mounted volume, it remains empty. Any ideas?

Thanks!

**Comment by ehazlett** [comment] 2016-04-06 14:15
This can be an issue with the volume.  I've updated how the configs are sync'd in my overlay PR.  Can you try the image `ehazlett/interlock:overlay` and see if that helps?

**Comment by aquavitae** [comment] 2016-04-08 09:18
I'm having exactly the same problem using 1.1.0 with nginx.  I've also tried mounting a host folder instead of using the docker volume.

**Comment by ehazlett** [comment] 2016-04-11 00:32
I will need to see logs from Interlock and the proxy containers as I can not reproduce.

**Comment by cnadeau** [comment] 2016-04-14 14:24
Here is a local setup to reproduce the original issue mentioned by @inf-rno 

https://github.com/cnadeau/swarmer/tree/interlock_issue_114_setup

had to tweak the script to remove the master from the swarm worker nodes and expose non TLS ports to be closer to our own setup

To create the full local swarm setup: 
./deploy.sh

docker exec -it swarm-agent-n1/swarmer_interlock_1 sh

haproxy fails at first because it doesn't find the file before interlock generates it, but even after the log mentioning it's created, the file is not generated inside the container: 

> interlock_1 | time="2016-04-14T14:17:39Z" level=info msg="interlock 1.1.0 (8a68c99)" 
interlock_1 | time="2016-04-14T14:17:39Z" level=debug msg="loading config from environment" 
interlock_1 | time="2016-04-14T14:17:39Z" level=debug msg="docker client: url=tcp://192.168.99.168:2375" 
interlock_1 | time="2016-04-14T14:17:39Z" level=debug msg="loading extension: name=haproxy" 
interlock_1 | time="2016-04-14T14:17:39Z" level=info msg="interlock node: id=4673a9e8aca81c1ab24321e19502d727761d1b2f4448e077984f278c34270865" ext=lb 
haproxy_1   | <7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
interlock_1 | time="2016-04-14T14:17:39Z" level=debug msg="starting event handling" 
haproxy_1   | [ALERT] 104/141811 (6) : Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
interlock_1 | time="2016-04-14T14:17:39Z" level=debug msg="event received: status=interlock-start id=0 type= action=" 
interlock_1 | time="2016-04-14T14:17:39Z" level=debug msg="notifying extension: lb" 
interlock_1 | time="2016-04-14T14:17:39Z" level=debug msg="triggering reload" ext=lb 
interlock_1 | time="2016-04-14T14:17:40Z" level=debug msg="reaping key: reload" 
interlock_1 | time="2016-04-14T14:17:40Z" level=debug msg="triggering reload from cache" ext=lb 
interlock_1 | time="2016-04-14T14:17:40Z" level=debug msg="checking to reload" ext=lb 
interlock_1 | time="2016-04-14T14:17:40Z" level=debug msg="updating load balancers" ext=lb 
interlock_1 | time="2016-04-14T14:17:40Z" level=debug msg="generating proxy config" ext=lb 
interlock_1 | time="2016-04-14T14:17:40Z" level=debug msg="proxy config path: /usr/local/etc/haproxy/haproxy.cfg" ext=lb 
interlock_1 | time="2016-04-14T14:17:40Z" level=debug msg="saving proxy config" ext=lb 

PS: huge thanks to @everett-toews for the swarmer script

**Comment by iiezhachenko** [comment] 2016-04-14 19:28
Looks like that is pretty common issue. Have the same in AWS with Docker Machine and Swarm.
Appeared last days.

I build Interlock by myself, in order to customise Nginx template.

**Comment by everett-toews** [comment] 2016-04-14 19:33
@iiezhachenko FWIW, you won't need to build Interlock yourself just to customize the templates once https://github.com/ehazlett/interlock/pull/113 merges (and there's an image for it).

**Comment by iiezhachenko** [comment] 2016-04-14 19:36
Well. I'm a DevOps, not Go developer. Solving my needs as I can :)
Waining for #113 to be merged. I really need that, because Nginx config is quite complex in my case.

**Comment by ehazlett** [comment] 2016-04-15 18:03
Ok I'm going to take a look and see if I can reproduce.  Thanks.

**Comment by timothysnave** [comment] 2016-04-19 15:05
Not sure if you're still investigating this, but I also get it this problem occasionally. If I shut it down and remove the containers, then wait for a little bit and run docker-compose up again, _sometimes_ it works. It's really hit or miss, though.

**Comment by danielbjornadal** [comment] 2016-04-21 11:03
I have the same problem when using volumes and haproxy.
interlock will not generate haproxy.cfg
```
$ ls -la /var/lib/docker/volumes/webloadbalancer_haproxy/_data/
drwxr-xr-x 3 root staff 4096 Apr 21 12:20 .
drwxr-xr-x 3 root root  4096 Apr 21 12:18 ..
drwxr-sr-x 2 root staff 4096 Apr  7 07:07 errors
```

**Comment by ehazlett** [comment] 2016-04-27 02:34
Can you try the latest `ehazlett/interlock:master` image?  I have some fixes there.

**Comment by danielbjornadal** [comment] 2016-04-27 18:27
@ehazlett When using the OPs configuration and :master, it create the volume and configuration, but if I start the web application in a separate docker-compose.yml file, after interlock and haproxy, it crashes saying that it cannot find the configuration file. If i try to start haproxy again, it works.

`423c997475dd        haproxy:latest               "/docker-entrypoint.s"   18 minutes ago       Exited (128) 4 minutes ago  `

```
<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
[ALERT] 117/180314 (6) : Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
<5>haproxy-systemd-wrapper: exit, haproxy RC=256
<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
[WARNING] 117/180315 (6) : config : log format ignored for frontend 'http-default' since it has no log address.
<7>haproxy-systemd-wrapper: SIGTERM -> 7.
<5>haproxy-systemd-wrapper: exit, haproxy RC=0

```

**Comment by ehazlett** [comment] 2016-04-27 19:58
Remove the volume.  Starting in 1.1.0 volumes are no longer needed.  My guess is something isn't writing properly.

**Comment by chromerobv** [comment] 2016-05-05 21:15
having similar problems. which volumes are no longer needed ?

**Comment by ehazlett** [comment] 2016-05-06 00:08
The ones that map to the proxy configs. Nginx or haproxy. That shouldn't
matter but I've seen some odd behavior. Also try using the latest
ehazlett/interlock:master to see if that helps. There are a couple of fixes
in there for reloading.

**Comment by chromerobv** [comment] 2016-05-06 00:16
yeah i have the latest master. i get no nginx.conf made. 

and just to clarify i should do something like this ?

```
docker run \
    -P \
    -d \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /opt/chromeriver/interlock/config.toml:/etc/config.toml \
    -v /opt/chromeriver/interlock/nginx-templates/nginx.conf.template:/etc/interlock/nginx.conf.template \
    ehazlett/interlock:master \
    -D run -c /etc/config.toml
```

basically removing the     -v nginx:/etc/conf

**Comment by ehazlett** [comment] 2016-05-06 00:55
Correct

**Comment by chromerobv** [comment] 2016-05-06 00:57
nope. still no config. 
```
time="2016-05-06T00:17:31Z" level=info msg="interlock 1.2.0-dev (2a79817)"
time="2016-05-06T00:17:31Z" level=debug msg="loading config from: file=/etc/config.toml"
time="2016-05-06T00:17:31Z" level=debug msg="docker client: url=tcp://ops-docker:2375"
time="2016-05-06T00:17:31Z" level=debug msg="loading extension: name=nginx"
time="2016-05-06T00:17:31Z" level=debug msg="using configuration template: file=/etc/interlock/nginx.conf.template" ext=lb
time="2016-05-06T00:17:31Z" level=info msg="interlock node: id=09ea508844600666c7f4db7d962dae231b961ea4efcb467374271da083595671" ext=lb
time="2016-05-06T00:17:31Z" level=debug msg="starting event handling"
time="2016-05-06T00:17:31Z" level=debug msg="event received: status=interlock-start id=0 type= action="
time="2016-05-06T00:17:31Z" level=debug msg="notifying extension: lb"
time="2016-05-06T00:17:31Z" level=debug msg="triggering reload" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="reaping key: reload"
time="2016-05-06T00:17:32Z" level=debug msg="triggering reload from cache" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="checking to reload" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="updating load balancers" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="generating proxy config" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="proxy config path: /etc/nginx.conf" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="proxyContainers: []" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="saving proxy config" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="signaling reload" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="triggering proxy network cleanup" ext=lb
time="2016-05-06T00:17:32Z" level=info msg="reload duration: 12.69ms" ext=lb
time="2016-05-06T00:17:32Z" level=debug msg="checking to remove proxy containers from networks" ext=lb
```

says it's doing it but no file is made.

**Comment by ehazlett** [comment] 2016-05-06 00:58
Can you post your interlock config?

**Comment by chromerobv** [comment] 2016-05-06 00:58
ListenAddr = ":8080"
DockerURL = "tcp://ops-docker:2375"
AllowInsecure = true
EnableMetrics = false

[[Extensions]]
  Name = "nginx"
  TemplatePath = "/etc/interlock/nginx.conf.template"
  ConfigPath = "/etc/nginx.conf"
  PidPath = "/etc/conf/nginx.pid"
  BackendOverrideAddress = "192.168.100.229"

**Comment by ehazlett** [comment] 2016-05-06 00:58
It's not finding any proxy containers.

**Comment by ehazlett** [comment] 2016-05-06 00:59
What does docker -H tcp://ops-docker:2375 ps report?

**Comment by chromerobv** [comment] 2016-05-06 01:13
so if i don't use the -v nginx:/etc/conf how should i start the nginx container? where do i point it to find the config ?

**Comment by ehazlett** [comment] 2016-05-06 01:49
See an example here:
https://github.com/ehazlett/interlock/blob/master/docs/examples/nginx-swarm-machine/

**Comment by paulopez78** [comment] 2016-05-06 12:12
Hi, I'm having the same issue.
When I don't use docker swarm it regenerates the nginx.conf file but when I use the swarm it doesn't work.
I've tried with a lot of configurations and different versions of interlock (including master)
When using docker swarm in the interlock logs you can see the events when you scale your containers but nginx.conf is not updated with these events.

that's the docker-compose.yml

version: "2"

services:
  interlock:
      image: ehazlett/interlock:master
      command: run
      tty: true
      ports:
        - 8080
      environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/var/lib/boot2docker/ca.pem"
            TLSCert = "/var/lib/boot2docker/server.pem"
            TLSKey = "/var/lib/boot2docker/server-key.pem"

            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/var/run/nginx.pid"
            TemplatePath = "/etc/interlock/nginx.conf.template"
            MaxConn = 1024
            Port = 80
      volumes:
        - ./nginx.conf.template:/etc/interlock/nginx.conf.template
        - /var/lib/boot2docker:/var/lib/boot2docker:ro
      restart: always

  nginx:
      image: nginx:latest
      entrypoint: nginx
      command: -g "daemon off;" -c /etc/nginx/nginx.conf
      ports:
        - 80:80
      labels:
        interlock.ext.name: "nginx"
      restart: always

**Comment by demaniak** [comment] 2016-05-10 11:08
I might be doing something stupid, but it seems this can be re-produced just with the example setup (see #147 )

**Comment by ehazlett** [comment] 2017-04-29 07:17
This should be fixed in the latest.  Please open a new issue if you continue to have issues.  Thanks!

**Closed by ehazlett** 2017-04-29 07:17 UTC
